### ISSUE TITLE
C# Dataset Tutorials in Research Environment Throw Errors

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Documentation#1389]
#### Expected Behavior

The C# tutorials in the [Research Environment > Datasets](https://www.quantconnect.com/docs/v2/research-environment/datasets/key-concepts) chapter run without errors.

#### Actual Behavior

If you copy-paste the code blocks from the tutorial into cells in the notebook, we get 
> System.ArgumentException: Unable to locate any exports matching the requested typeName: QuantConnect.Queues.JobQueue (Parameter 'typeName')
   at QuantConnect.Util.Composer.GetExportedValueByTypeName[T](String typeName, Boolean forceTypeNameOnExisting) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Common/Util/Composer.cs:line 307
   at QuantConnect.Lean.Engine.LeanEngineSystemHandlers.FromConfiguration(Composer composer) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Engine/LeanEngineSystemHandlers.cs:line 109
   at QuantConnect.Lean.Engine.Initializer.GetSystemHandlers() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Engine/Initializer.cs:line 65
   at Submission#3.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
   at QuantConnect.Util.Composer.GetExportedValueByTypeName[T](String typeName, Boolean forceTypeNameOnExisting) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Common/Util/Composer.cs:line 307
   at QuantConnect.Lean.Engine.LeanEngineSystemHandlers.FromConfiguration(Composer composer) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Engine/LeanEngineSystemHandlers.cs:line 109
   at QuantConnect.Lean.Engine.Initializer.GetSystemHandlers() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Engine/Initializer.cs:line 65
   at Submission#3.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

because 
```
#load "../Initialize.csx"
```
needs to be in its own cell.

We also get 
> (4,9): error CS0305: Using the generic type 'PrimitiveDataFrameColumn<T>' requires 1 type arguments
(5,44): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<dynamic>' to 'System.Collections.Generic.IEnumerable<decimal?>'
(6,44): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<dynamic>' to 'System.Collections.Generic.IEnumerable<decimal?>'
(7,43): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<dynamic>' to 'System.Collections.Generic.IEnumerable<decimal?>'
(8,45): error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<dynamic>' to 'System.Collections.Generic.IEnumerable<decimal?>'
Error: compilation error

when trying to create a C# DataFrame.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by DerekMelchin** [comment]
The Plot Data tutorials on these pages also need review 
- Some are missing the header bar on the code blocks
- In the C# version, the first sentence should link to our Plot Net docs page
- Some of the tutorials request historical data, some don't.

Should be able to run all of the code blocks on the entire page without error

**Comment by AlexCatarino** [comment]
The `Initialize.csx` issue solved by https://github.com/QuantConnect/Documentation/commit/ac885fed646925bca58d973a743dee3373c16c86.
